### ISSUE TITLE
offsetParent should return an option?

### ISSUE THREAD

**Issue by stuartkeith** [reasonml-community/bs-webapi-incubator#101]
`offsetParent` can return null (a common situation is recursively walking up the DOM until `offsetParent` returns `null` - i.e. the `body` element has been reached).

However, the binding of `offsetParent` does not return an option - so this case is not detectable and can cause an exception.

The following fixed it for me:

`[@bs.get] [@bs.return nullable] external offsetParent : HtmlElementRe.t => option(Dom.element) = "";`

Thanks!

**Comment by glennsl** [comment]
Indeed. Would you like to make a PR for it?
