### ISSUE TITLE
type signatures for pixel count accessors

### ISSUE THREAD

**Issue by gittheking** [reasonml-community/bs-webapi-incubator#102]
in the event of the user increasing / decreasing the level of zoom in their browser, `Dom.Window.scrollY`, `Dom.Element.offsetTop`, etc. will return return floats rather than integers. Current type signatures make it difficult to account for this in a sane manner.

Chrome 67.0.3396.99 / Firefox 60.0.1 - OS X 10.13.3

**Comment by zploskey** [comment]
This is the spec on this topic: https://drafts.csswg.org/cssom-view/

I can get `window.scrollY` and `window.scrollX` to return floating point values in Chrome and Firefox, and the spec says it should be a `double`, so a `float` for our purposes. Same for `pageXOffset` and `pageYOffset`, which are aliases for them respectively.

Additionally, `Window` functions `scroll`, `scrollTo` and `scrollBy` currently take ints but should be floats.

I haven't yet been able get `offsetTop` to give me anything but integer values, and the spec says that it should be a `long` (https://drafts.csswg.org/cssom-view/#extensions-to-the-htmlelement-interface), same as `offsetLeft`, `offsetWidth`, and `offsetHeight`. I think these are fine to remain ints unless there are browsers that in practice use floats for these.

Element's `scrollLeft` and `scrollTop` are ints but should be floats based on the spec.

Based on this information, I propose:

- In `Window` change `scrollY`, `scrollX`, `pageXOffset` and `pageYOffset` properties to be floats.
- Also in `Window`, make `scroll`, `scrollTo` and `scrollBy` functions take floats.
- In `Element`, change `scrollLeft`, `scrollTop` and corresponding setters `setScrollLeft` and `setScrollTop` to use floats.

**Comment by glennsl** [comment]
FYI: I'm waiting to see if I can get #103 through before I do a new major release.
