### ISSUE TITLE
More complete bindings for URL

### ISSUE THREAD

**Issue by bryanthomaschen** [reasonml-community/bs-webapi-incubator#108]
I've created the bindings for [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) and [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) at https://github.com/bryanthomaschen/bs-webapi-incubator/blob/feature/implement-url/src/file/UrlRe.re

Would this be an appropriate addition to `bs-webapi`?

**Comment by glennsl** [comment]
Very much. Would you make a PR?

**Comment by bryanthomaschen** [comment]
PR opened! - https://github.com/reasonml-community/bs-webapi-incubator/pull/109

**Comment by glennsl** [comment]
Thanks! Closing this in favor of the PR then
