### ISSUE TITLE
Bug with Url bindings

### ISSUE THREAD

**Issue by bryanthomaschen** [reasonml-community/bs-webapi-incubator#110]
When doing:
```
let url = Webapi.Url.make("http://www.example.com");
Js.log(url->Webapi.Url.hostname);
```
The generated javascript is:
```
console.log(url.hostname());
```
This causes an error as the property is not a function.

Should change `[@bs.send.pipe : t]` to `[@bs.get]`

**Comment by glennsl** [comment]
This isn't really a bug. `->` is pointless, broken, and should not be used. `|>` is the proper pipe operator, as used by OCaml and the rest of the functional programming world.

**Comment by glennsl** [comment]
Sorry, I got confused, You are right!

**Comment by bryanthomaschen** [comment]
I completely agree with your view on `->`

**Comment by glennsl** [comment]
Yeah, apparently it confuses me even in cases where it works exactly the same as `|>` :)

Just released a new patch version with this fix.
