### ISSUE TITLE
FocusEvent relatedTarget should be optional

### ISSUE THREAD

**Issue by wezm** [reasonml-community/bs-webapi-incubator#112]
FocusEvent relatedTarget is defined to always return something but there are times when it may be null.

### Refereces

* https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent#Properties
* https://codepen.io/wezm/pen/MqRROW

https://github.com/reasonml-community/bs-webapi-incubator/blob/e936b2e23d59583aef5e5cec0739777856021f93/src/dom/events/FocusEventRe.re#L9

**Comment by glennsl** [comment]
Fixed. Thanks!
