### ISSUE TITLE
URLSearchParams.get returns incorrect type

### ISSUE THREAD

**Issue by SamWyld** [reasonml-community/bs-webapi-incubator#122]
Currently the type of `get` in URLSearchParamsRe.re is:
`[@bs.send.pipe : t] external get: string => option(string) = "";`

As you can see in the documentation [here](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get)

The type I think should be:
`[@bs.send.pipe : t] external get: string => Js.Nullable.t(string) = "";`

Quite happy to make a PR if I am correct about this :)

**Comment by glennsl** [comment]
Indeed it should, thanks! Closing in favor of #123.
