### ISSUE TITLE
Canvas set size

### ISSUE THREAD

**Issue by userbq201** [reasonml-community/bs-webapi-incubator#124]
How to set width and height to canvas ? 
I must write declaration like follow code ?
```js
[@bs.set] external setWidth : (Dom.element, int) => unit = "width";
[@bs.set] external setHeight : (Dom.element, int) => unit = "height";
```
and then
```js

  setWidth(canvas, ElementRe.clientWidth(DocumentRe.documentElement(document)));
  setHeight(canvas, ElementRe.clientHeight(DocumentRe.documentElement(document)));
```
or has any solution ?

**Comment by glennsl** [comment]
That looks about right, unless you have any issues with it. If you submit a PR for the externals we can include them in `CanvasElement` so you don't have to define them yourself though.

**Comment by userbq201** [comment]
@userbq201 ok. I'll submit PR
