### ISSUE TITLE
Missing "navigator"

### ISSUE THREAD

**Issue by malthe** [reasonml-community/bs-webapi-incubator#134]
E.g.
```ocaml
external navigator: navigator = "" [@@bs.val]
external userAgent: string = "" [@@bs.val] [@@bs.scope "navigator"]
```

**Comment by glennsl** [comment]
`Window.navigator` is present, but it's not been implemented further. I'd happily accept a PR that implements it.

I don't like to use issues as a TODO-list though, so I'll close this. But if you have questions about it, feel free to post them here.
