### ISSUE TITLE
Convert Dom.eventTarget to Dom.element

### ISSUE THREAD

**Issue by kadfak** [reasonml-community/bs-webapi-incubator#135]
I've been investigating how to convert a `Dom.eventTarget` to `Dom.element` for the target element to be useful. I've found nothing from webapi's sources, but a blog post suggested using 
```
external asDomElement : 'a => Dom.element = "%identity";
```
Although it works, I'd like to know if this is the best way to achieve it.

Example where such conversion is needed:
```reason
let onDocumentClick = ({ReasonReact.state}, event) =>
  Webapi.Dom.(
    switch (state.menuRef^) {
    | Some(menu) =>
      let target = event->MouseEvent.target;
      Js.log(menu |> Element.contains(target)); /* target's type causes error */
    | None => ()
    }
  );
```

Error output:
```
This has type:
  Dom.eventTarget (defined as Dom.eventTarget_like(Dom._baseClass))
But somewhere wanted:
  Dom.node_like('a) (defined as Dom.eventTarget_like(Dom._node('a)))

The incompatible parts:
  Dom._baseClass
    vs
  Dom._node('a)
```

**Comment by kadfak** [comment]
I found an [SO answer](https://stackoverflow.com/questions/47263238/pass-results-of-queryselectorall-to-eventtarget-addeventlistener) that gives enough context about this problem.

For the record:
```
Short answer:

external eventTargetToNode : Dom.eventTarget => Dom.node = "%identity";

An eventTarget can be almost anything, and there's unfortunately no good way of figuring
out what it is. In JavaScript it's simply inferred by the user based on context (It might be
possible to carry that context around in a type parameter, but that's off in the future
somewhere).

So for the moment you'll have to make an unsafe cast to get what you need.
```

**Comment by paulshen** [comment]
There's also [`EventTarget.unsafeAsElement`](https://github.com/reasonml-community/bs-webapi-incubator/blob/870865ba279297e22c3025ce0fdea16d4d0bbe5a/src/Webapi/Webapi__Dom/Webapi__Dom__EventTarget.re#L327). still unsafe but you don't have to write your own.

```js
let target = event->MouseEvent.target;
Js.log(menu |> Element.contains(EventTarget.unsafeAsElement(target)));
```
