### ISSUE TITLE
Please provide an example for BeforeUnloadEvent

### ISSUE THREAD

**Issue by christinwhm** [reasonml-community/bs-webapi-incubator#151]
Hi @glennsl, I am wondering how I could use https://github.com/reasonml-community/bs-webapi-incubator/blob/bc0badfc40420e271f4b1703dd9c43bed7d68b13/src/Webapi/Webapi__Dom/Webapi__Dom__BeforeUnloadEvent.re to stop user from reloading/exiting the current page, it's appreciated if you could provide an example, cheers

**Comment by glennsl** [comment]
Something like this should work I think:

```ml
open Webapi.Dom;
Window.addEventListener("beforeunload", Event.preventDefault);
```

**Comment by christinwhm** [comment]
@glennsl thanks a lot, :)

**Comment by christinwhm** [comment]
@glennsl this is what I've come up with:

```
let onBeforeUnload = (e: Dom.event) => {
   Webapi.Dom.Event.preventDefault(e);
  Js.log(e);
};

Webapi.Dom.(
    React.useEffect0(() => {
      Window.addEventListener("beforeunload", onBeforeUnload, window);

      Some(
        () =>
          Window.removeEventListener("beforeunload", onBeforeUnload, window),
      );
    })
  );
```

the above code is supposed to print the shape of `e` once the user is leaving the site, but it's not ..., I am wondering what I did wrong with above code
