### ISSUE TITLE
Nodelist forEach

### ISSUE THREAD

**Issue by dmartinjs** [reasonml-community/bs-webapi-incubator#155]
Hello,

I'm new to ReasonML but I made search 
and it seams it lack forEach loop on Nodelist.

Currently, we have to use Array.forEach :
```ocaml
let items = Document.querySelectorAll(".item")(document);

Js.Array.forEach(item => Js.log(item), NodeList.toArray(items));
```

that output :
```javascript
var items = document.querySelectorAll(".item");

Array.prototype.slice.call(items).forEach((function (item) {
        console.log(item);
        return /* () */0;
      }));
```

With NodeList.forEach :
```ocaml
let items = Document.querySelectorAll(".item")(document);

Js.NodeList.forEach(item => Js.log(item), items);
```

that should output:
```javascript
var items = document.querySelectorAll(".item");

items.forEach((function (item) {
        console.log(item);
        return /* () */0;
      }));
```

**Comment by glennsl** [comment]
Hmm, it might have been left out because browser support is very recent. Or just forgotten. I can't see any good reason for not having it included now though. Want to add it in a PR?

**Comment by dmartinjs** [comment]
I'm trying,
but not comfortable with bindings yet.

So the result is not a success for now.

Do you have suggestions for good ressources for learn ?
