### ISSUE TITLE
discussions about namespace

### ISSUE THREAD

**Issue by bobzhang** [reasonml-community/bs-webapi-incubator#18]
I noticed that all files in such package ends with `Re`,
maybe we can add a style field in bsconfig, like 
```
  { namespace : "re",   format: "suffix"}
```
So that the build system will generate a map file for only exported units

re.ml
```ocaml
module CssDeclaration = CssDeclarationRe
```

So that ender users could call `Re.CssDeclaration` with auto-completion.

Two issues:
1. which style would be better suffix vs prefix
(seems convention is prefix based: https://github.com/ocaml/ocaml/pull/1010)
2. Should we reuse package name 
3. We can hide the complexity by generating prefix even for in-source packages, but as you said, companies like unique file name (this is the same with Bloomberg), we can delay this a little bit

**Comment by chenglou** [comment]
Can we do just 2? You're talking about generating a module alias file right?

**Comment by bobzhang** [comment]
yes, just generating a module alias, but reason-js is not a vaild suffix or prefix

**Comment by chenglou** [comment]
Ah I remember: npm doesn't allow uppercase letters anymore, so the only choice the user has is snake_case. This probably sucks for camelCase. So let's not reuse package name...?

**Comment by glennsl** [comment]
Couldn't the package name just be transformed to snake_case? I'd like that for module names derived from (dasherized) filenames too. It's a simple and predictable process, and while there is a minute chance of accidental collisions it seems essentially theoretical to me.

**Comment by chenglou** [comment]
@glennsl what if we want the module to be called `ReasonJs` rather than `Reason_js`?

**Comment by glennsl** [comment]
Then I suppose you'd have to specify it, but you would have to do that either way, right? Having a generated default wouldn't change that.

**Comment by bobzhang** [comment]
`ReasonJs` looks better, it is acceptable to have all files renamed form 'xxRe' to 'ReasonJs_xx', too ugly ?

**Comment by bobzhang** [comment]
btw, if we enforce such convention, then the build system could infer the package name, is a good idea?

**Comment by jaredly** [comment]
I dunno if this is coming from the right direction. I guess it's cool to look at the current convention and say "how can we adapt our build tools to make this better", but the real problem is that there's no notion of namespacing beyond that of a file. Doing funky things with the file name is, like, a cool hack, but hey we've got folders!! which provide a super great way of organizing files...
Could we instead adopt rust semantics for namespacing, where each folder essentially becomes a module?

**Comment by glennsl** [comment]
@jaredly I'd really like that, but I'm guessing the heavy reuse of ocaml's toolchain makes that difficult. I've heard rumours that ocaml might gain support for some form of namespacing sometime in the next decade or so, though!

@bobzhang I'd be fine with that. I'd be fine with anything, really, as long as it's not gibberish.

**Comment by bobzhang** [comment]
cool, I will whip up a quick solution, stay tuned, btw, do you use `open` too much?

**Comment by chenglou** [comment]
We have package names that also have `.` in it. For starter, just a `{"namespace": ...}` would be good enough.

I don't dislike @jaredly proposal either. But we can at least do a library-wise namespace first.

**Comment by glennsl** [comment]
@bobzhang I don't understand the question, Do you think I use `open` too much? `ReasonJs` and `ReasonJs.Dom` is kind of designed to be `open`ed, like a core library, though it could certainly use some cleaning up here and there.

**Comment by glennsl** [comment]
Closing for having outlived its usefulness, I think. There's namespace support in BS now. See #81
