### ISSUE TITLE
Canvas2d.putImageData creates erroneous calls when not using all the optionals.

### ISSUE THREAD

**Issue by fhammerschmidt** [reasonml-community/bs-webapi-incubator#180]
Here is  a repro:
https://codesandbox.io/s/gifted-platform-rffze?file=/src/index.js

**Comment by glennsl** [comment]
Hmm, that's unfortunate. I think the only fix here is to split the binding in two. One with just the `x` and `y` arguments, and another with all the `dirty` arguments as well, all mandatory.

**Comment by fhammerschmidt** [comment]
Yeah, that's my guess, too.
When you call it with less arguments it even says it only allows arity of 3 or 7, so there is not really any optional argument there.

**Comment by yawaramin** [comment]
@fhammerschmidt if you would like to give this a shot, I would recommend the following:

- Change the type of `putImageData` to not take the extra params
- Add a new binding for `putImageDataWithDirtyRect` that requires all of the parameters
