### ISSUE TITLE
Bsdoc dependency makes contributing a bit difficult on Linux

### ISSUE THREAD

**Issue by TomiS** [reasonml-community/bs-webapi-incubator#188]
Postinstall crashes on Linux because of the `bsdoc` dependency. Looking at bsdoc repository I realize this is probably expected. I can of course circumvent this problem by by saying `npm install --ignore-scripts`, but doing that causes tests not to work. "You need to have postinstall enabled", they say.

**Comment by yawaramin** [comment]
Hmm, yeah, that does make it difficult. I think the best solution here would be to publish bsdoc binaries for Linux and Windows and I'll close this issue once I do that. But in the meantime could I ask you to work around this by deleting bsdoc from the `package.json`? Sorry about the inconvenience...

**Comment by yawaramin** [comment]
@TomiS hi, I decided to remove `bsdoc` as a devDep and make it a `peerDep`. Now installing it separately during the Travis build. This should take care of the postinstall issue.
