### ISSUE TITLE
unmet peer dependency warning

### ISSUE THREAD

**Issue by TheSpyder** [reasonml-community/bs-webapi-incubator#200]
I posted this comment [on the commit that caused it](https://github.com/reasonml-community/bs-webapi-incubator/commit/31fdb220e4903390ec961b7b51616fe574fb4b5e), but maybe that doesn't trigger a notification.

I understand what you're trying to do with this change, but there are no `peerDevDependencies`. This now brings up a warning when installing `bs-webapi`:
`warning " > bs-webapi@0.19.1" has unmet peer dependency "bsdoc@^6.0.4-alpha".`

**Comment by yawaramin** [comment]
Hey, thanks, been meaning to remove that dep but in the meantime if you send a PR I'll be happy to merge.
