### ISSUE TITLE
Regarding document.documentElement.scrollTop

### ISSUE THREAD

**Issue by mattdamon108** [reasonml-community/bs-webapi-incubator#202]
Hi, team.

First of all, thank you for your great work. 👍 

I found the change log that `scrollTop` was changed to return `float` instead of `int`. ([change log](https://github.com/reasonml-community/bs-webapi-incubator/blob/master/CHANGELOG.md#0110---2018-08-02)) I'm wondering it seems different from the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) which says it is `int` value.

```
// Get the number of pixels scrolled.
var intElemScrollTop = someElement.scrollTop;

// Set the number of pixels scrolled.
element.scrollTop = intValue;
```

Is there any reason to change the return value to `float`?

**Comment by glennsl** [comment]
The rationale is explained in #102

**Comment by mattdamon108** [comment]
@glennsl Clear! Thanks!
