### ISSUE TITLE
How to use addEventListener on window

### ISSUE THREAD

**Issue by MargaretKrutikova** [reasonml-community/bs-webapi-incubator#206]
Maybe I am missing something obvious, but I really can't find a way to do simple `window.addEventListener`.

Has this functionality disappeared with the new release?
Thanks!

**Comment by hesxenon** [comment]
huh? As far as I can see it's still available through `Webapi.Dom.Window.addEventListener`? The Window module [includes EventTarget.Impl](https://github.com/reasonml-community/bs-webapi-incubator/blob/master/src/Webapi/Dom/Webapi__Dom__Window.re#L104)?

**Comment by yawaramin** [comment]
Yes, this should do the job: https://reasonml-community.github.io/bs-webapi-incubator/api/Webapi/Dom/Window/#val-addEventListener

Any issues using that @MargaretKrutikova ?

**Comment by MargaretKrutikova** [comment]
Oh, yes, my apologies!
I got some errors trying to update version of bucklescript and everything else related 🙂 It works with
```
Webapi.Dom.Window.addEventListener("scroll", handleScroll, Webapi.Dom.window);
```

Thank you for pointing this out!
