### ISSUE TITLE
What should the convention be for constants?

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-webapi-incubator#27]
`_MyConstant`, `_MY_CONSTANT` or something else entirely?

**Comment by chenglou** [comment]
`_MyConstant` is kind of an awkward middle between `myConstant` and `_MY_CONSTANT`. I prefer `myConstant` but maybe we got counterexamples.

**Comment by glennsl** [comment]
Some more context on different types of constants, how the JS API implements them and how they're currently modeled in reason-js: 
* Enum values:
  * In JS: [`PROCESSING_INSTRUCTION_NODE`](https://developer.mozilla.org/en/docs/Web/API/Node/nodeType#Node_type_constants)
  * Current implementation in `Dom`: Variant with type constructors in the form of e.g. `ProcessingInstruction`
  * Current implementation in `Gl`: `let` binding in the form of e.g. `_LINE_STRIP`
* Bitmask flags:
  * In JS: [`SHOW_DOCUMENT_TYPE`](https://developer.mozilla.org/en-US/docs/Web/API/NodeIterator/whatToShow)
  * Current implemtnation in `Dom`: module with `let` bindings in the form of e.g. `WhatToShow._DocumentType`
  * Current implementation in `Gl`: `le`t binding in the form of e.g. `_STENCIL_BUFER_BIT`

**Comment by chenglou** [comment]
let bindings shouldn't be necessary there right? Just externals? I don't know why those are lets.

Since we do use variants too, we can probably be idiomatic here and use `lineStrip`, `documentType` and `stencilBufferBit`? Hopefully this doesn't clash with an actual `lineStrip` variable?. Otherwise it should probably be `_LINE_STRIP`, etc.

**Comment by glennsl** [comment]
externals would be more verbose, I guess?

It feels a bit inconsistent to me to have bitmask flags in camelCase while enums, being modeled as variants, would have to be PascalCase. But in either case they should probably both be wrapped in type-specific modules, which would make name collisions a non-problem.

**Comment by chenglou** [comment]
Verbose is fine; consumers wouldn't notice the difference. They also don't create additional bindings and get inlined.

**Comment by glennsl** [comment]
I think I'm leaning towards the following:

enums:
```reason
module NodeType = {
  type t =
  | Element
  | Attribute
  | ...

  let encode : t -> string = ...
  let decode : string -> t = ...
};
```

bitmask flags:
```reason
module WhatToShow = {
  type t;

  external all : t = "NodeFilter.SHOW_ALL" [@@bs.val];
...
  external processingInstruction : t = "NodeFilter.SHOW_PROCESSING_INSTRUCTION" [@@bs.val];
...
};
```

**Comment by chenglou** [comment]
humm that's a bit much. Not sure we should take the occasion to rearrange things like this. I still prefer either `myConstant` or `_MY_CONSTANT`

Btw I've also used quite a few `[@@bs.val]` this way. @bobzhang are things like `NodeFilter.SHOW_ALL" [@@bs.val]` ok?

**Comment by glennsl** [comment]
I'm not sure I understand. Converting the variants to `external`s would be a much bigger rearrangement, is non-idiomatic and misses out on exhaustiveness-checking. And not namespacing with a module will require namespacing in the names themselves (The variants are already overlapping, but they can be, because they're variants).

The bitmask flags is already a module, in part because it provides a function to safely compose the flags. This should probably be functionality provided by some standard library or other, but there's of course no consensus on that either yet (I have my own implementation in rebase though).

**Comment by bobzhang** [comment]
it depends on how those enum variant will be used, will you do `OPEN | WRITE` or not?

**Comment by glennsl** [comment]
For the `WhatToShow` bitmask flags type I have a (poorly named) `many` function that will `lor` flags together in a type safe manner. I'd like to keep the type abstract.
