### ISSUE TITLE
Should enum variants fail on encode or decode?

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-webapi-incubator#29]
Or should enums have an Unknown variant that encodes to some nonsense that will break something later (current approach, mostly)?

**Comment by chenglou** [comment]
Ehhh, cc @bobzhang @rickyvetter @IwanKaramazow. It'd be great to have a good answer for decoding variants and such.

**Comment by glennsl** [comment]
More context:

I've manually written encode and decode functions for stringly-typed enums, of which there are a lot. Sometimes I raise an exception when the unexpected happens (https://github.com/BuckleTypes/reason-js/blob/master/src/fetch/fetchRe.re#L53), other times I add an extra `Unknown` variant and wait for it to blow up somewhere else (https://github.com/BuckleTypes/reason-js/blob/master/src/dom/htmlElementRe.re#L7)

**Comment by chenglou** [comment]
^ might be better to model this as an option or something, if it's not inconvenient.

**Comment by glennsl** [comment]
To me, an option seems a bit less convenient than just having an `Unknown` variant It's also not always clear what `None` would mean, since `None` or `Default` (encoded as `""`) are sometimes also actual values. So you might get `Some None` perhaps.

Then there's the a difference between whether the source of the value is from the "system", as e.g. `nodeType` would be, or if it's user-specified via an html attribute perhaps. In the former case, unless the spec changes and someone uses an obsolete version of reason-js, it really ought to be an exceptional occurrence to receive an ill-formed string value. In the latter case, when the user might type in whatever they damn well please, they should perhaps have an `Unknown` variant or be wrapped in an `option` or something similar.

**Comment by chenglou** [comment]
option was just an example. I'm talking about not throwing, like [here](https://github.com/BuckleTypes/reason-js/blob/4007244842050dcb75e137f9710e4297d1176bec/src/fetch/fetchRe.re#L83)

**Comment by bobzhang** [comment]
I would just like something simpler

```
external fetchAsync : (_ [@bs.as "async"])  -> string -> t 
```
This works better with code completion

**Comment by glennsl** [comment]
@bobzhang That only works for a small subset of use cases though.

Consider `nodeType`, which is used on `Dom.node` to express whether it is actually a `Dom.element` or `Dom.document` etc. Then it needs to be a variant that can be pattern matched in order to do the right thing. (Or some other way of doing the same thing).

Or consider any of the variants in `fetch` that's used with several different data structures. Using inline polymorphic variant types would mean a lot of duplication, messy ffi signatures and a much greater risk of a bug sneaking through when the variants need to be altered (These are web specs, they change all the time).
