### ISSUE TITLE
How do we make element creation and lookup both type safe and convenient.

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-webapi-incubator#43]
As it is now you create an element by doing `document |> Document.createElement "img"` which gives you an `element` that you'll then have to cast down to an `htmlImageElement` to be able to use it with functions specific to that type of element. Even though you know damn well that you've just created an `htmlImageElement` the type system does not. So how do we force-feed it?

1. Add element-specific create methods, e.g. `HtmlImageElement.create`. Can we then hard-code this to `document.createElement` or are elements bound to a specific document instance?

2. Could we use GADTs somehow? e.g.
```ml
type elementType =
| ...
| HtmlImageElement : <put magic here> -> htmlImageElement

let imageElement = document |> Document.createElement HtmlImageElement
```

The issue is similar with `getElementsByTagName` and perhaps other functions.

**Comment by mransan** [comment]
You could do something like:
```OCaml
type image 

external src : image -> string -> unit = "" [@@bs.set]
(* .. add function on image *) 

type paragraph
(* .. add function on paragraph *)

type link
(* .. add function on link *)

type _ kind = 
  | Image : image kind
  | Paragraph : paragraph kind 
  | Link : link kind 

module Document : sig 

  type t 

  val dom : t 

  val createElement : t -> 'a kind -> 'a 

end = struct 

  type t 

  external dom : t = "dom" [@@bs.val]

  external createElementEx : t -> string -> 'a = "createElement" [@@bs.send]
 
  let createElement : 
    type a. t -> a kind -> a = 
    fun t kind ->
      match kind with
      | Image -> createElementEx t "img"
      | Paragraph -> createElementEx t "p"
      | Link -> createElementEx t "a"

end

let ()  = 
  let img1 = Document.createElement Document.dom Image in 
  src img1 "blah.jpg";
  let p1 = Document.createElement Document.dom Paragraph in 
  src p1 "blah.jpg" (* Compilation Error *)
```

**Comment by glennsl** [comment]
@mransan Thanks! This is precisely what I was thinking of, but unable to actually formulate.

So then we'd have to maintain a massive variant, and a massive match in createElement and any other similar functions., as opposed to maintaining a whole boatload of separate functions in each element's module.

What does this mean for the extensibility and maintenance of the API as the DOM and HTML specifications change? This is of course the classic expression problem, but which is more important for a DOM API, the ability to easily add new kinds, or the ability to easily add new functions that operate on them?

Pros:
- We won't need to add otherwise empty modules for element interfaces that don't add any additional functionality.
- `getElementsByTagName` would certainly be more intuitive to use
- This could theoretically be used even for functions such as `getElementById`
- Is user extensible
- The same pattern could be applied to e.g. nodeType.

Cons:
- Will produce a big switch that adds to code size and runtime cost for each function that will use this
- Confusing interaction with subtyping?

I'm just thinking out loud here. What are your thoughts on the tradeoffs?

**Comment by mransan** [comment]
Regarding getElementById, you would also have to do some check to make sure the element tag name is matching the GADT constructor no ?

**Comment by glennsl** [comment]
Yeah you'd have to check the `tagName`, which I doubt we want to do for the default "getElementById", but we could perhaps have an overload that does it. But it's nice to have the option at least, and it will probably be useful for other functions too.

**Comment by mransan** [comment]
Definitely something like:
```OCaml 
val safeTagNameCast : 'a -> 'b kind -> 'b 
```
Could be re-used!

**Comment by mransan** [comment]
@glennsl I need to understand the subtyping better before making an opinion :)

**Comment by glennsl** [comment]
Understandable. Fortunately I wrote [an essay](https://github.com/BuckleTypes/reason-js/pull/23) on it :grin:
