### ISSUE TITLE
Document.asHtmlDocument fails when no doctype is defined

### ISSUE THREAD

**Issue by jmorrell** [reasonml-community/bs-webapi-incubator#66]
<img width="565" alt="particles demo - playfulreasonml 2017-06-11 20-05-51" src="https://user-images.githubusercontent.com/175496/27018518-0749db92-4ee6-11e7-8b70-03cfae8cfc80.png">

https://github.com/BuckleTypes/bs-webapi-incubator/blob/master/src/dom/nodes/documentRe.re#L6

I hit this when my test HTML file didn't have a doctype defined. It might be reasonable to require a doctype declaration, but the error message was not helpful until you looked at the code. Something about `"name"` of `undefined`.

**Comment by glennsl** [comment]
Thanks. Just to reiterate my thoughts from Discord, it might be better (and more ergonomic even) to just drop the fragile heuristics and add some `unsafeAs...` functions instead.

**Comment by glennsl** [comment]
Fixed in https://github.com/reasonml-community/bs-webapi-incubator/commit/54d3460605b1c5b0bb9085d97bac372fd77df613
