### ISSUE TITLE
Rename htmlElementRe

### ISSUE THREAD

**Issue by bloodyowl** [reasonml-community/bs-webapi-incubator#69]
Given that the spec calls this `DocumentElement` and that `HTMLElement` is something else, this is very confusing. Don't you think renaming the module `DocumentElement` would help make it easier?

**Comment by glennsl** [comment]
You lost me. Where does the spec call it `DocumentElement`?

**Comment by bloodyowl** [comment]
Here `HtmlElement` is elements with a `html` tag: https://github.com/BuckleTypes/bs-webapi-incubator/blob/master/src/dom/html/htmlElementRe.re#L4-L5

My bad, the spec calls it `HTMLHtmlElement`, I got confused because it its often referred to as `document.documentElement`.

Although, in the spec, `HTMLElement` is a subclass of `Element` https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement, which is hard to disambiguate here with the bs-webapi naming

**Comment by glennsl** [comment]
Which are hard to disambiguate? `HTMLElement` is both a subtype of and inherits the implementation of `Element` in `bs-webapi`.

**Comment by bloodyowl** [comment]
`Element` ⬅ `HTMLElement` ⬅ `HTMLHtmlElement`

**Comment by glennsl** [comment]
Right, yea that certainly isn't unconfusing, but I think we should stick with the spec here, for consistency. These bindings are meant to be pretty low-level, upon which more friendlier APIs can be built, but it's kind of hard to build anything on ground that's full of holes and keeps moving :)
