### ISSUE TITLE
Update version, createText is still in the latest

### ISSUE THREAD

**Issue by thomas-jeepe** [reasonml-community/bs-webapi-incubator#76]
`createText` is still in the latest when installed from npm, meaning I can't create text nodes :(.

The commit that handled it was https://github.com/reasonml-community/bs-webapi-incubator/commit/1d8a29833bb6677a49d9ccf2ac6245c85680b5bf

The version just needs to be bumped and published to npm. Thanks :)

**Comment by glennsl** [comment]
Done. Thanks for the nudge!

**Comment by glennsl** [comment]
Btw, you can make npm install the master branch from github by putting `reasonml-community/bs-webapi-incubator` in you package.json instead of the version.

**Comment by thomas-jeepe** [comment]
Thanks :)
