### ISSUE TITLE
offsetParent returns int

### ISSUE THREAD

**Issue by rsaccon** [reasonml-community/bs-webapi-incubator#79]
https://github.com/reasonml-community/bs-webapi-incubator/blob/master/src/dom/html/HtmlElementRe.re#L50

Shouldnt it return an Element ?

> The HTMLElement.offsetParent read-only property returns a reference to the object which is the closest (nearest in the containment hierarchy) positioned containing element. 

from: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

**Comment by glennsl** [comment]
Indeed it should. Thanks for reporting!
