### ISSUE TITLE
Activate namespaces

### ISSUE THREAD

**Issue by arnarthor** [reasonml-community/bs-webapi-incubator#81]
Wouldn't it make senes to activate namespaces in this project? I see that the Bs_webapi module was deprecated in favour of Webapi but I still think it makes sense to activate namespaces here.

We're using this for some shimmed APIs in React Native but we needed to vendor this package to activate namespaces because both projects have a file called ImageRe.re

**Comment by glennsl** [comment]
Renaming `Bs_webapi` to `Webapi` was actually done in preparation of namespaces. I've just not gotten around to flipping the switch yet. Feel free to submit a PR if you've done so in a fork. I'll then just have to publish it to the `@reasonml-community` org.

**Comment by arnarthor** [comment]
Yeah, I have it ready in a fork. I'll submit a PR when the additional bindings I added have been merged, that way I can change that part a tiny bit so I don't need to have the indirection of FileRe.re for example.

**Comment by glennsl** [comment]
It's been merged :)

**Comment by yawaramin** [comment]
Any further thoughts on this? Is namespacing still a go?

**Comment by yawaramin** [comment]
Oh, I see @arnarthor did a PR but there were some complications, #82 

If you all don't mind I would like to try a different approach to this, which I discussed in my post recently: https://dev.to/yawaramin/a-modular-ocaml-project-structure-1ikd

It would preserve all the user-visible module hierarchies and the file structure would look like this:

```
src
├── Webapi
│   ├── Webapi_Base64.re
│   ├── Webapi_Canvas
│   │   ├── Webapi_Canvas_Canvas2d.re
│   │   └── Webapi_Canvas_WebGl.re
│   ├── Webapi_Canvas.re
│   ├── Webapi_Dom
│   │   ├── Webapi_Dom_AnimationEvent.re
│   │   ├── Webapi_Dom_Attr.re
...
│   │   ├── Webapi_Dom_WheelEvent.re
│   │   └── Webapi_Dom_Window.re
│   ├── Webapi_Dom.re
│   ├── Webapi_File.re
│   └── Webapi_Url.re
└── Webapi.re
```

There would be no incompatible changes for anyone using the aliased modules, like `Webapi.Dom.Element`, and no conflicts with modules like BuckleScript's `Dom`.

**Comment by glennsl** [comment]
Yeah, this is my preferred method of namespacing as well (The `Re` suffix was a facebook convention that I think they've dropped internally now as well), although I think you should use double underscores to be consistent with how it's usually done in OCaml, since single underscore is typically used as word separator there.

The `Dom` module is a pain in the ass in other ways too, and I think the best resolution is to transition it to `Js.Dom`, but that's going to take some time in any case.

**Comment by yawaramin** [comment]
Cool, sending a PR in a few.

**Comment by TomiS** [comment]
@yawaramin Hey. I realize I'm a bit late to the party and also abusing issues a bit, but I'd like to know why you ended up with double underscores instead of just one in this library? Are there any good reasons for that other than maybe some aesthetic preference?

**Comment by yawaramin** [comment]
@TomiS see https://github.com/reasonml-community/bs-webapi-incubator/issues/81#issuecomment-482942005 :-)

**Comment by TomiS** [comment]
@yawaramin Ah, I understand you're following the convention from your article here. However, your article suggest one underscore but this library uses two. I was just wondering if there is a specific reason for that, that I should also consider.
