### ISSUE TITLE
Missing *_to_opt annotations

### ISSUE THREAD

**Issue by abdullahibnnadjo** [reasonml-community/bs-webapi-incubator#88]
Hi, similarly to #49, several FFI functions returning a `'a option` miss a `[@@bs.return (undifined|null)_to_opt]`, which breaks any `match` afterwards (getting `undefined` through `Some`).

I found this when trying to use: https://github.com/reasonml-community/bs-webapi-incubator/blob/f0db37ba32f2d02ca4cb66f13cc67bda9230b255/src/dom/nodes/NodeListRe.re#L7

But it seems that a bunch of other functions are suffering from the same issue, like https://github.com/reasonml-community/bs-webapi-incubator/blob/f0db37ba32f2d02ca4cb66f13cc67bda9230b255/src/dom/nodes/NodeRe.re#L7 or https://github.com/reasonml-community/bs-webapi-incubator/blob/f0db37ba32f2d02ca4cb66f13cc67bda9230b255/src/dom/traversal/NodeIteratorRe.re#L9-L10 etc

**Comment by glennsl** [comment]
Fixed. Thanks for reporting!
