### ISSUE TITLE
cancelAnimationFrame is not supported

### ISSUE THREAD

**Issue by collinwright** [reasonml-community/bs-webapi-incubator#89]
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame), `requestAnimationFrame` should return a `long`, which can then be passed to its sister function `cancelAnimationFrame` to abandon the animation request before it is rendered. However, the Webapi module currently only exports `requestAnimationFrame : ((float) => unit) => unit`.

**Comment by glennsl** [comment]
Fixed. Added `requestCancellableAnimationFrame` and `cancelAnimationFrame`. Thanks for reporting!

**Comment by MoOx** [comment]
@glennsl I am curious about the origin of `requestCancellableAnimationFrame`. I can't find any reference to it on the web. Is this a real thing?

**Comment by MoOx** [comment]
Oh I just understand why this thing exist 😄
