### ISSUE TITLE
"Cannot find module 'bs-platform/lib/js/curry.js' from 'bs-webapi/src/dom/nodes/ElementRe.js'" error when used with brunch

### ISSUE THREAD

**Issue by GoNZooo** [reasonml-community/bs-webapi-incubator#94]
Hi,

I've stumbled upon this error when trying to integrate bucklescript into our JS for a project. We don't currently have the possibility to change the build system so I'm stuck with brunch.

Building with `bsb` isn't really an issue, but on page load when trying to use `bs-webapi` I get the following error:

```
Cannot find module 'bs-platform/lib/js/curry.js' from 'bs-webapi/src/dom/nodes/ElementRe.js'
```

This, to me, seemed strictly like a brunch issue until I tried using another library to see if it actually was a general issue. `bs-fetch` is usable even though it also depends on `bs-platform`. I'm not sure if this is just because of dead code elimination and it ends up not using any modules from `bs-platform`, though.

`bs-platform` is at v2.2.3
`bs-webapi` is at v0.8.3

**Comment by glennsl** [comment]
I don't know anything about burnch, but apparently it's not bundling all the dependencies. Why I don't know. `bs-fetch` depends on `curry.js` as well, but not in a nested module, so maybe that makes a difference.

I'm afraid there's not much more I can do to help.
