### ISSUE TITLE
docType -> doctype?

### ISSUE THREAD

**Issue by svsool** [reasonml-community/bs-webapi-incubator#95]
https://github.com/reasonml-community/bs-webapi-incubator/blob/24cee2500b9c98355a14896fa9fc4ceb8a3e2258/src/dom/nodes/DocumentRe.re#L24

Hi! Why does it have `docType` name and not a `doctype`? To me it looks it should be `doctype` https://www.w3schools.com/jsref/prop_document_doctype.asp
https://developer.mozilla.org/en-US/docs/Web/API/Document/doctype

**Comment by glennsl** [comment]
Indeed, thank you! Fixed and released in 0.9.1
